### ISSUE TITLE
Feature Request: Ability of using the plugin as a replacement for the Backlinks core plugin?

### ISSUE THREAD

**Issue by nhan000** [TfTHacker/obsidian42-strange-new-worlds#100]
My FR is that SNW plugin can follow the active notes as the core Backlinks does. Currently I need to click the reference counter for the notes every time I want to see the backlinks to it (quite tiring if I'm traversing many notes).

I'd like the SNW have 2 panels (users can drag 1 above and 1 below in the sidebar). One would act as the Backlinks plugin, change according to the active notes. The other would act as how it currently is (stickied for the reference that you actively click).

Thanks so much for making this plugin!

**Comment by Glint-Eye** [comment]
+1 I think thats a good idea.

**Comment by nhan000** [comment]
Closed because this plugin [Better Search Views](https://github.com/ivan-lednev/better-search-views) fulfils this feature request.

**Comment by nhan000** [comment]
Closed because this plugin [Better Search Views](https://github.com/ivan-lednev/better-search-views) fulfils this feature request.
