### ISSUE TITLE
[Feature Request] Allow to hide references coming to daily notes

### ISSUE THREAD

**Issue by satkowski** [TfTHacker/obsidian42-strange-new-worlds#101]
Hey,

Within my daily notes, I often summarize what I did over the day and refer to the notes I created or updated. However, it is a little bit annoying to see a rather extensive list of references where two-thirds only come from daily notes. Therefore, it would be nice to have the option to ignore links coming from daily notes. Or, that daily note references are at the bottom of the list, to allow one to easier find the references in other notes.

Kind regards,
Marc

**Comment by TfTHacker** [comment]
Hi there, I am not 100% tracking. Would one of the frontmatter directives solve the issue?

https://tfthacker.com/Obsidian+Plugins+by+TfTHacker/Strange+New+Worlds/Frontmatter+directives+for+SNW

Specifically:
- snw-index-exclude
- snw-file-exclude

Or is it simply a sorting issue?

**Comment by satkowski** [comment]
Hey,

I don't think one of the front matter directives can achieve my proposal. Let's re-iterate again. I would like an option to either (1) remove(hide daily notes from showing in SNW reference view. Or (b) have the option to change the sorting, where the daily notes are presented at the bottom.

I like daily notes. However, I don't see a specific need to see that a daily note from 3 weeks ago has linked to a given document. My interest in relations between other content documents is far greater.

You already provided the option to exclude references from files with the "exclude files" option of obsidian. It is more or less the same, but only for daily notes. I could place my daily note folder in this list, however, this makes them unavailable for any other use.

**Comment by Benature** [comment]
Hi, I have the same feature request.

I want my daily notes to be excluded from link counting. But I do not want to exclude my daily notes folder from Obsidian.

May I ask for adding a textarea in the settings of SNW, the paths in the textarea (separated by comma) are only excluded in SNW plugin but not Obsidian?

**Comment by TfTHacker** [comment]
After further review, I have decided against adding this feature. However, there is a directive you can use on properties to prevent a page from being included in the reference index.

[https://tfthacker.com/Obsidian+Plugins+by+TfTHacker/Strange+New+Worlds/Frontmatter+directives+for+SNW](https://tfthacker.com/Obsidian+Plugins+by+TfTHacker/Strange+New+Worlds/Frontmatter+directives+for+SNW)

**Comment by satkowski** [comment]
I tried out your proposal again. However, I can't get my feature request to work with those YAML tags. Could you please explain to me exactly how I should use them?

If I understood it correctly, `snw-index-exclude` will remove the link **to** this document. And `snw-file-exclude` will only **turn off** SNW on this page. But both will not enable my feature request to **remove** the specific file (or in my wish folder) from being counted in **other** files.

Kind regards,
Marc
