### ISSUE TITLE
[Feature Request] Compatibility with Link Range plugin

### ISSUE THREAD

**Issue by ParkerRobb** [TfTHacker/obsidian42-strange-new-worlds#102]
The [Link Range](https://github.com/rmellmer/obsidian-link-range) plugin allows one to link to a range of headings using a `[[note#h1..h2]]` syntax. SNW does not seem to see these types of links, as they do not appear in any reference counters. What is the feasibility of getting SNW to see these links, given that it uses the Obsidian link cache?

**Comment by TfTHacker** [comment]
This is a cool plugin, but it is basically adding its own linking system to Obsidian. Obsidian doesn't have native support for what this plugin is doing and thus isn't reflected in its internal database. SNW uses the internal database to identify these links. Unfortunately, it is beyond until Obsidian adds this natively, which I would like!
