### ISSUE TITLE
[Feature Request] Modify counter appearance

### ISSUE THREAD

**Issue by ParkerRobb** [TfTHacker/obsidian42-strange-new-worlds#103]
I use a dark background, and I find it especially hard-to-impossible to see the counters in the gutter. Is there currently any way to change the color of the counters?

**Comment by nhan000** [comment]
Yes. Check out these links
- https://github.com/TfTHacker/obsidian42-strange-new-worlds/discussions/19
- https://github.com/TfTHacker/obsidian42-strange-new-worlds/discussions/18

**Comment by ParkerRobb** [comment]
Thanks! I did not see those over in the Discussions.
