### ISSUE TITLE
SNW Counters in Properties

### ISSUE THREAD

**Issue by Comprehensive-Jason** [TfTHacker/obsidian42-strange-new-worlds#105]
Obsidian 1.4 released Properties, which provides a new visual editor for YAML metadata that works with internal links. 

Currently, SNW does not show counters for links in Properties. Could this be added?

**Comment by TfTHacker** [comment]
This is a great idea. I had already been wanting something like this, but this might be the right time to add it. How would you visualize it appearing? 

For example, a count of how many times the property is used? How about the value if reused? (This one I am not sure bout).

**Comment by TfTHacker** [comment]
This is now supported since 2.1. Sorry I forgot about your request here.
