### ISSUE TITLE
Counters overlap with Tasks checkboxes and mess with indentations in Reading/Preview mode

### ISSUE THREAD

**Issue by dljsjr** [TfTHacker/obsidian42-strange-new-worlds#106]
Already mentioned in https://github.com/TfTHacker/obsidian42-strange-new-worlds/issues/39 but I'm still seeing this issue in a clean test vault with no themeing, SNW 1.2.2:

![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/444635/ee17e69d-4f4d-4874-aeb4-9fea093a89b3)
![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/444635/6736e23f-f9b0-40b8-aee2-9d28d9e8ff3d)

![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/444635/74249e3f-3a02-4f71-a206-29a43b96d123)

![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/444635/af6f0ab5-4938-4549-93da-55ad47780cff)

**Comment by TfTHacker** [comment]
A fix for this should be available in the next public release. It can be tested now if you like with BRAT and the current beta.
