### ISSUE TITLE
Have popup view appears below the count number?

### ISSUE THREAD

**Issue by nhan000** [TfTHacker/obsidian42-strange-new-worlds#109]
I usually want to click the count number to open the SNW pane in the sidebar.

Currently the default behavior is to have the popup appear to the right of the indicator:

https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/85216095/ed578bf1-7a58-42e5-8131-14491a28ce75

But if I open the pane too close to the right sidebar, the popup overlaps the indicator and I can't click that number anymore:

https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/85216095/f0dc72c9-9d7a-498a-b32a-ba71f0aa13df

I think this behavior would be best: to the side, but also below the number indicator. (I have no idea what would trigger the behavior below, but I think it should be the default behavior?)

https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/85216095/875dddeb-f5d2-4329-a697-2843d2c51f81

**Comment by TfTHacker** [comment]
I think this is behaving better in recent versions, but it can still be a bit unpredictable.
