### ISSUE TITLE
FR: Trigger Popup when hovering link / link under cursor

### ISSUE THREAD

**Issue by chrisgrieser** [TfTHacker/obsidian42-strange-new-worlds#11]
Nice plugin idea!

I noticed that the popup only shows when you hover the number next to the link. Since those popups are quite small, it's a bit annoying to target them for the popup. I suggest implementing one or both of the following alternative methods for showing the popup:
1.  The popup appears when you hover the link
2. add a command that shows the popup for the link under the cursor

While solution 2 would only work in Source Mode / LP, it does have the advantage of being a solely -keyboard-driven method for using the plugin, for those of us who detest using the mouse 😉

**Comment by TfTHacker** [comment]
do you think hovering over link and getting popop could be annoying though as well, especially if text has multiple links?

Also, the little numbers are easily modifiable with CSS. I went to some length to make sure it would be fairly customizable by overwriting CSS selectors from style.css of plugin.

**Comment by chrisgrieser** [comment]
> do you think hovering over link and getting popop could be annoying though as well, especially if text has multiple links?

well you could simply add a small delay before the popup appears, so there aren't accidental triggerings. Can be done with a one liner in css with [`transition-delay`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-delay). Alternatively, the aforementioned command to trigger the popup for the link under the cursor would also completely prevent accidental triggering.

> Also, the little numbers are easily modifiable with CSS. I went to some length to make sure it would be fairly customizable by overwriting CSS selectors from style.css of plugin.

That does not help much imv, since making it easier to hover the numbers essentially means making sufficiently big numbers, which in turn would make the note less readable.
