### ISSUE TITLE
Note title and body are misaligned when plugin is active

### ISSUE THREAD

**Issue by christeefy** [TfTHacker/obsidian42-strange-new-worlds#111]
Hi there! I've been using this plugin recently and it's pretty sweet!

However, recently I've been noticing my note's title and body to be misaligned, as follows:
![Screenshot 2023-08-24 at 9 50 39 AM](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/8013575/bea9bf1a-29d3-4d6b-823b-709c78208526)

Today I realized that this only occurred when the Strange New World plugin is activated. 
With it disabled, the issue is fixed:
![Screenshot 2023-08-24 at 9 50 59 AM](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/8013575/e844ac96-9a9c-4377-b435-c48330e72f4f)

I'm currently on Obsidian v1.3.7 and SNW v1.2.2.

Let me know if you need more information for this and how I can help to fix the issue.

**Comment by TfTHacker** [comment]
Yes, this is related to themes. It is because a gutter is being added. You can disable the reporting in the gutter in Settings for SNW if you don't want to see them.

Some themes work just fine with this.

**Comment by christeefy** [comment]
Thanks!
