### ISSUE TITLE
[BUG]Links on the canvas are not counted

### ISSUE THREAD

**Issue by jiajiala** [TfTHacker/obsidian42-strange-new-worlds#112]
Links on the canvas are not counted

**Comment by TfTHacker** [comment]
I acknowledge that this issue exists. It stems from the fact that links within an embedded note on Canvas are not indexed by Obsidian, meaning they don't appear in the backlinks pane.

As of now, there is no solution. However, I will keep this issue open and monitor any updates to the API.

For additional context: https://forum.obsidian.md/t/canvas-cards-and-notes-in-links-backlinks-and-outgoing-arrows-in-graph-view/49697/47

**Comment by TfTHacker** [comment]
I don't think Obsidian is going to address this so I am going to close this issue. Honestly, as soon as they add it to the API, it should work in SNW since SNW uses the obsidian API to get information on the linking in the vault.
