### ISSUE TITLE
Imcompatibility with Dataview inline fields in Reading view

### ISSUE THREAD

**Issue by RyotaUshio** [TfTHacker/obsidian42-strange-new-worlds#116]
Hi, thank you so much for this great plugin. I'd like to report an imcompatiblity issue with Dataview.

In the sandbox vault with Dataview 0.5.64 & SNW 1.2.3 installed, create a note with the following content:
```md
[link :: [[Start Here]]]
```

Then, it is rendered as below in the reading view:
<img width="253" alt="image" src="https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/72342591/8319fd87-e8a2-477e-9c7b-d63b0b55e042">

As you can see, the SNW indicator is doubled. The same happens for the `(link :: [[Start Here]])` syntax as well. Hope this will be fixed in the future. Thank you!

**Comment by TfTHacker** [comment]
A fix for this should be available in the next public release. It can be tested now if you like with BRAT and the current beta.

**Comment by RyotaUshio** [comment]
I can confirm the problem has gone. Thank you so much for your effort!
