### ISSUE TITLE
Feature Request: copy all blocks rendered in popup

### ISSUE THREAD

**Issue by Yubuxin** [TfTHacker/obsidian42-strange-new-worlds#12]
Thanks for your hard work and this amazing plugin idea at first. 

I think adding a "copy all" button to the popups of SNW may help a lot to the card-writing workflow, is this possible to implement?

**Comment by TfTHacker** [comment]
tnx for your idea. can you give me more context. you would want to copy all the contents? or all the block references?

**Comment by Yubuxin** [comment]
@TfTHacker Just all the block references would be great, and maybe add a blank line between blocks so that the copied content can form the first draft of a new article.

**Comment by TfTHacker** [comment]
Can you give me a usage scenario? I think I understand the feature, but curious why someone would need this?
