### ISSUE TITLE
Counter not showing for headers with identifiers

### ISSUE THREAD

**Issue by w-zhiwei** [TfTHacker/obsidian42-strange-new-worlds#120]
Works fine for paragraph block, but there's no counter for headers.

![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/31446914/554d85d6-a987-4176-b2c8-cdd489f47697)

**Comment by TfTHacker** [comment]
Thank you for reporting this issue. I recently rewrote the SNW indexing engine, and I could not reproduce the problem during my testing. So, I'm hoping that it has been fixed. I plan to release the beta version as 2.0.0 soon, and I hope you will all be able to test it and report on whether it is working.

If you'd like to test it now, please install the plugin using BRAT. Version 1.2.7 is the beta version and includes the intended fixes.
