### ISSUE TITLE
Will insert a gutter at the beginning of the current editing table cell from Obsidian v.1.5.* 

### ISSUE THREAD

**Issue by lethefrost** [TfTHacker/obsidian42-strange-new-worlds#121]
The plugins `lapel` and `obsidian42-strange-new-worlds` both insert a gutter, so the current workaround is to make sure both are turned off if you want to remove the gutter. Waiting for a fix. Thank you for developing and maintaining this plugin! ❤️

**Comment by TfTHacker** [comment]
So for the delay in responding. In Settings you can disable the gutter block reference counter, while the rest of SNW keeps showing reference counters. Have you tried that?
