### ISSUE TITLE
Counter matching Note13 -> Note-1#3

### ISSUE THREAD

**Issue by evantravers** [TfTHacker/obsidian42-strange-new-worlds#123]
If you create the following notes:

`Note-1.md`
```markdown
# Note-1

##### 3

This is a test
```

and

`Test.md`
```markdown
Link to non-existing [[Note-13]].
```

Then SNW will show a bubble indicating that `Note-1#3` is being linked to.

**Comment by ParkerRobb** [comment]
I've been experiencing the same problem for a while. I have a Bible text divided into one file per chapter and one heading per verse, and SNW erroneously displays counters for the first so many verses of every chapter, depending on how many chapters are in the book. Here's a screenshot of SNW mistaking `[[1Sa 21]]` for `[[1Sa 2#1]]`: 

![Screenshot 2023-12-26 at 16 12 12](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/62605621/88f01daf-bdad-4e8f-a086-b74b7c0cb50e)

**Comment by miknight71** [comment]
I am having the same issue as @ParkerRobb. I too am using the markdown Bible and want to use it with SNW. But, one of the best features of of SNW, the link counter to headings, is creating false connections just as Parker stated. 
![IMG_4153](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/1953300/bf3ee435-6df9-4b59-9161-eb4939949eb2)

As can be seen, connections are being made where none exist.

**Comment by TfTHacker** [comment]
Thank you all for reporting this issue. I recently rewrote the SNW indexing engine, and during my testing, I was unable to reproduce the problem. Thus, I am hopeful that it has been fixed. I am planning to release the beta version as 2.0.0 soon, and I hope you will all be able to test it and report back on whether it is working.

If you wish to test it now, please install the plugin using BRAT. The version 1.2.7 is the beta and includes the intended fixes.

**Comment by ParkerRobb** [comment]
@TfTHacker were you able to reproduce the issue before the plugin rewrite?

**Comment by TfTHacker** [comment]
I didn't try before the rewrite :-), but I tried duplicating it lat night.

**Comment by evantravers** [comment]
I've been looking for this bug to reproduce recently and can not, so I must assume that the rewrite was successful. Well done sir!
