### ISSUE TITLE
Cannot read properties of null listItems

### ISSUE THREAD

**Issue by devinat1** [TfTHacker/obsidian42-strange-new-worlds#124]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'listItems')
    at new ContextBuilder (plugin:obsidian42-strange-new-worlds:3048:31)
    at grabChunkOfFile (plugin:obsidian42-strange-new-worlds:3215:26)
    at async getUIC_Ref_Item (plugin:obsidian42-strange-new-worlds:3205:25)
    at async getRefAreaItems (plugin:obsidian42-strange-new-worlds:3418:41)
    at async getUIC_Ref_Area (plugin:obsidian42-strange-new-worlds:3347:24)
    at async getUIC_Hoverview (plugin:obsidian42-strange-new-worlds:3447:25)
    at async eval (plugin:obsidian42-strange-new-worlds:4023:9)

![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/15788108/dedb84ea-898e-4c4d-9bf1-c2b8f3f7c75c)

Not sure how to reproduce, but this error occurs when creating a new note.
Obsidian config:
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.3.5
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 38
	Plugins enabled: 26
		1: Readwise Official v2.0.1
		2: Dataview v0.5.64
		3: Calendar v1.5.10
		4: Templater v1.18.3
		5: Todoist Plugin v1.11.1
		6: Admonition v10.1.1
		7: Recent Files v1.3.8
		8: Minimal Theme Settings v7.3.1
		9: Excalidraw v2.0.10
		10: Kanban v1.5.3
		11: Periodic Notes v0.0.17
		12: Commander v0.5.1
		13: LanguageTool Integration v0.3.5
		14: Obsidian42 - Strange New Worlds (SNW) v1.2.3
		15: Paste URL into selection v1.7.0
		16: QuickAdd v1.6.1
		17: Settings Search v1.3.10
		18: Advanced Tables v0.19.1
		19: Taskbone v1.2.3
		20: Plugin Update Tracker v1.5.2
		21: Homepage v3.6.0
		22: Hider v1.3.1
		23: Linter v1.21.0
		24: Note Refactor v1.8.2
		25: Global Hotkeys v0.1.2
		26: Custom Frames v2.4.6

**Comment by TfTHacker** [comment]
Thank you for reporting this. This issue should have been addressed in the last update.
