### ISSUE TITLE
BUG 🐞: Linking SNW Sidebar to a Tab disappears when switching to a different note

### ISSUE THREAD

**Issue by VerAn1015** [TfTHacker/obsidian42-strange-new-worlds#128]
I expect the behavior of linking the SNR sidebar to a tab would make it so that when I switch to a different note, the SNW sidebar updates to the current note. However, the current behavior is that when changing to a new note, the SNW sidebar disappears and a restart of obsidian is needed to get it back. 

Linked SNW Sidebar BEFORE switching to a different note
![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/148541981/c98b4e4d-ac6c-448f-8674-3c4712008811)

Linked SNW Sidebar AFTER switching to a different note
![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/148541981/b202db4f-005e-473d-9d39-ddb0ddf7e17f)
As seen in the image, when switching to a different note, the SNW sidebar changes to what the switched note is.

**Comment by TfTHacker** [comment]
This is an interesting idea. Actually, SNW is not designed to be used with the tab sync feature, and for now, I don't plan to add that. It is more for ephemeral reference.
