### ISSUE TITLE
BUG: Strange Behavior in Canvas Tables

### ISSUE THREAD

**Issue by Friedolito** [TfTHacker/obsidian42-strange-new-worlds#129]
Found this peculiar bug: 

In canvas, when inserting tables in a markdown note,  it will focus the cursor on the right side, rather then left.

Disabling SNW and the behaviour stops. 

![Screenshot_-2024-02-14_at_19 34 19](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/53973194/c00515f6-c04c-4953-80d6-2004906e6f4c)

SNW Version: 1.2.5
obsmd Version 1.5.5

Happy to give more information if relevant. 
Thank you for developing SNW! :)

**Comment by danieltomasz** [comment]
Similar behaviour is happening in the markdown file, the cursor is centered instead being on the left (minimal theme seems to mitigate this behavior but the error persist in vanilla theme)

**Comment by TfTHacker** [comment]
Thank you for reporting this.

This is a side effect of the gutter feature of SNW, which cannot be fixed as various themes handle gutters differently. In general, if its is conflicting with your workflow, you can toggle this off:

<img width="760" alt="image" src="https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/69121180/32a7ae08-eec5-45b2-b848-96d1e39a0720">
