### ISSUE TITLE
Hotkey to turn off and on

### ISSUE THREAD

**Issue by kmaustral** [TfTHacker/obsidian42-strange-new-worlds#13]
This is a wonderful tool for connecting thoughts and notes. But when I'm more in task mode, I prefer a less cluttered interface. It would be very hand to be able to turn this off and on, like the graph.

**Comment by TfTHacker** [comment]
Great idea!

**Comment by TfTHacker** [comment]
This feature is now implemented as a command palette feature. It toggles SNW off temporarily (until restart) and can of course be toggled back on with the same CP command.

Tnx for enhancement request.

**Comment by kmaustral** [comment]
Great to hear. I'll save it up for my knowledge weaving sessions.
