### ISSUE TITLE
Incompatibility with the plugin mathlinks

### ISSUE THREAD

**Issue by math-feng** [TfTHacker/obsidian42-strange-new-worlds#130]
Double links that have been rendered by the plugin mathlinks won't be able to show the number of references, i.e. the superscript number

**Comment by TfTHacker** [comment]
I am not a user of Mathlinks. However, there was a similar issue with other plugins, which I have now addressed in the latest beta of SNW. If possible, could you please install the beta along with BRAT and check if the issue has been resolved?

If not fix, could you provide me with a sample document so I can replicate the issue?

Given that I believe this problem will be resolved, I am going to close the issue. However, feel free to reopen it if the issue persists.
