### ISSUE TITLE
Feature Request - Linking words and their abbreviations as one 

### ISSUE THREAD

**Issue by sunsurfsnow** [TfTHacker/obsidian42-strange-new-worlds#132]
It would be great to be able to link words and their abbreviations together. For example, "Cardiovascular Disease" and "CVD" being  linked. 

This would allow notes to use expanded definition at the beginning of a note and the use the shorted abbreviation for the remainder, as is done in most scientific writing.

Thanks for the great work,

**Comment by TfTHacker** [comment]
I am curious if you are referring to alias? so if an alias is defined, it would be used as a counter?

**Comment by sunsurfsnow** [comment]
I guess it depends on how you would define alias? 

It would be ideal if I could write as following>

[[Cardiovascular Disease]] increases in response to.......  [[CVD]] risk factors include ........

Idealy both are linked so all Cardiovascular Disease and CVD results are shown (and counted) when search for either term.

I hope that is more clear and answers your question.

thanks for the previous update on capitalisation!!!! Great work.

**Comment by TfTHacker** [comment]
Sorry for the long overdue response. This is what aliases are designed to do (though they don't work exactly the way you laid out in your example). SNW does support alias named links.
