### ISSUE TITLE
Ghost link references cause incorrect reference behavior in Reading Mode

### ISSUE THREAD

**Issue by jjaychen1e** [TfTHacker/obsidian42-strange-new-worlds#133]
When a note includes at least one ghost link, the reference count is incorrect in Reading Mode (but is correct in Editing Mode).

In this case, let define the first reference as `r1`, all rest references will show the same reference count as `r1.count`, and the popover window also shows the information about `r1`.

**Comment by TfTHacker** [comment]
Thank you for reporting this issue. I recently rewrote the SNW indexing engine, and I could not reproduce the problem during my testing. So, I'm hoping that it has been fixed. I plan to release the beta version as 2.0.0 soon, and I hope you will all be able to test it and report on whether it is working.

If you want to test it now, please install the plugin using BRAT. Version 1.2.7 is the beta version and includes the intended fixes.

**Comment by seomwan** [comment]
@TfTHacker I think maybe the references need to have dots `.` in their names, so for example:

- `[[A]]` would show `100`
- `[[A.b]]` would also show `100`, when it should be `10`

Those are correct for both Live and Source Mode.
This is on SNW 2.0.2

**Comment by seomwan** [comment]
Btw, I think counts should not be displayed in Source mode, but that's probably another issue (mentioned because it may simplify implementation of this)

**Comment by TfTHacker** [comment]
This is a good catch. I was able to reproduce the issue. Actually it revealed that many ghost file scenarios were not handled correctly. I hope to release 2.0.3 today, please feel free to test that and see if it is better.

Regarding source mode, please open a FR if you think that would be a good idea.
