### ISSUE TITLE
Unable to turn off SNW on embeds

### ISSUE THREAD

**Issue by jques17** [TfTHacker/obsidian42-strange-new-worlds#134]
I embedded a picture via copy and paste and saw it had a counter on it so I tried turning off the embeds in the settings and reopening the note. Unfortunately, that did not work. Below are the things I've tried:

1. Deleting the picture and copy-pasting again.
2. Restarting Obsidian
3. Turning off SNW, turning it back on again. 
4. Turning off SNW, turning it back on again, and restarting Obsidian

**Comment by TfTHacker** [comment]
Thank you for reporting this. I am wondering if you have the counter for gutters turned on? These only show counts for embeds that are full lines, like pictures. Perhaps turn off the gutter counter and see if it gives you the desired results. Please keep in mind that only embeds are displayed in the gutter, so by turning this off you won't lose any other counters.
