### ISSUE TITLE
invalidation

### ISSUE THREAD

**Issue by yyy000213123** [TfTHacker/obsidian42-strange-new-worlds#135]
the newest update causes problem. The quoted entity  cannot show menu of this plugin.
Thanks for your development.

**Comment by TfTHacker** [comment]
Could you please provide a little more detail. In what context are you getting this message. Which action?

**Comment by yyy000213123** [comment]
The sign is ok in old version，but in new version，it can not display truely

**Comment by yyy000213123** [comment]
[张宇考研数学基础30讲【高等数学分册】 (1).md](https://github.com/TfTHacker/obsidian42-strange-new-worlds/files/15457748/30.1.md)
this is the file which have problem

**Comment by TfTHacker** [comment]
Please test again in 2.2.0, the most recent update. Thank you for the sample file. If it isn't working, please provide a small, simple file illustrating the problem. This file had a lot of stuff I couldn't read and didn't want to load in my vault.
