### ISSUE TITLE
When the SNW pane is closed, how to reopen a new SNW pane?

### ISSUE THREAD

**Issue by zhao414** [TfTHacker/obsidian42-strange-new-worlds#136]
on the SNW pane, right click on the title,  chose "close". The SNW pane is closed.

However, there is no way to reopen a new pane, other than close and reopen obsidian.

**Comment by zhao414** [comment]
This is really a fast reaction! 
Thank YOU!

**Comment by zhao414** [comment]
> Thank you for reporting this. It is is now fixed with the 2.1.1 release.

I have updated to 2.1.1. 
I find a way to open the new pane of SNW, but I am not sure this is the only way.

I move the mouse point to the SNW labels next to a link. In the pop-uped SNW floating window, I click the 3-dots in the floating window, then the SNW pane appears in the right side-area in the Obsidian.

Is this the only way to open/reopen the SNW pane? I thought a command in the command pane will be more intuitive, like the other plugins.

**Comment by TfTHacker** [comment]
Yes it is the only way. The pane doesn't do anything until you have click on one of the reference counters.
