### ISSUE TITLE
FR: Counts should not be displayed in Source mode

### ISSUE THREAD

**Issue by seomwan** [TfTHacker/obsidian42-strange-new-worlds#137]
Basically all plugins render their content in Live mode and Reading view, and do nothing in Source mode.

I usually use Source mode as a fallback to edit without the distractions and glitches that can happen in Live mode.
SNW is the only plugin so far that goes against my expectations.
It makes it difficult to select stuff on mobile, and copy pasting can output weird garbled characters.

As a workaround, I can turn it off on mobile temporarily, but it's an extra step I have to do in addition to switching modes every time I need to view / edit.

**Comment by seomwan** [comment]
Just FYI, I originally mentioned this in another issue: https://github.com/TfTHacker/obsidian42-strange-new-worlds/issues/133#issuecomment-2053937316

**Comment by TfTHacker** [comment]
Thank you for your suggestion. This issue has been addressed in the 2.1.2 release. It is toggled off by default but can be toggled on in the settings.
