### ISSUE TITLE
Can NOT show the amount of references beside headings' block-id 

### ISSUE THREAD

**Issue by exam-ple** [TfTHacker/obsidian42-strange-new-worlds#138]
Even the latest version(2.1.2) has the same problem
https://github.com/TfTHacker/obsidian42-strange-new-worlds/issues/120#issue-2001357512

Can NOT show the amount of references beside headings' block-id 

> Works fine for paragraph block, but there's no counter for headers.
> 
> ![image](https://private-user-images.githubusercontent.com/31446914/284131616-554d85d6-a987-4176-b2c8-cdd489f47697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjQxOTEsIm5iZiI6MTcxNDMyMzg5MSwicGF0aCI6Ii8zMTQ0NjkxNC8yODQxMzE2MTYtNTU0ZDg1ZDYtYTk4Ny00MTc2LWIyYzgtY2RkNDg5ZjQ3Njk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE3MDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YzcwOWFkNjlhMzcxNGQ0MmNmOTg4Y2NkMmQ5MmM5ZTE5NzIxNDUwMDYzMmMzOGU5OGIwMjhjYWY3NWMwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W1aQYrWRx51SN2Upg11kw7YiGitwuH3BH88-w2MWItU)

**Comment by TfTHacker** [comment]
Can you provide me sample markdown, the source file and destination file?

**Comment by exam-ple** [comment]
@TfTHacker 
It's easy to reproduce the problem
![240506-224417](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/66286339/92e05db2-4ef1-4ae2-8372-0344d04073ea)

As the image you can see, if the block-id is not at heading(like ^ex1), it will show counter. But if the block-id is at heading(like ^ex2), counter won't be showed(there's no counter number beside 'heading  ^ex2')

**Comment by Apc57** [comment]
Why does the "number of links" not shown next to the new link and shown below?

**Comment by jiajiala** [comment]
I ran into the same problem, which is useful because ^xxx helps distinguish the title with the same name, but after the title, there is no way to display the reference count

**Comment by TfTHacker** [comment]
SNW isn't supporting block id's on a header. It will work in some scenarios, but its coincidental. I'm not planning to add support for this at this point.
