### ISSUE TITLE
BUG: Disabling "Incoming Links Header Count" disables references in properties

### ISSUE THREAD

**Issue by Comprehensive-Jason** [TfTHacker/obsidian42-strange-new-worlds#139]
Disabling "Incoming Links Header Count" in plugin settings also disables "show references in properties", regardless of how "show references in properties" is set in plugin settings. 

Here's a gif of the issue in my Sandbox vault:
![Recording2024-05-09054656-ezgif com-video-to-gif-converter](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/68677082/c294ed8d-d0b0-49a0-a029-58546962aa32)

**Comment by TfTHacker** [comment]
This should now be addressed with update 2.2.0. Thank you for reporting this issue.
