### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by daxmonson** [TfTHacker/obsidian42-strange-new-worlds#14]
Cool idea and it's working well on desktop. Installed via Brat on mobile and the little popovers aren't showing up after enabling it. Saw the commit for mobile so figure it is supported. Let me know if I can do anything to help and thanks for making this.

**Comment by TfTHacker** [comment]
Would you please check the installed version number on your mobile device.  I am sure my changes are pushed out (though going to rebuild just in case).

**Comment by daxmonson** [comment]
0.0.26 now 0.0.27 and the update seemed to go fine via BRAT, it still wasn't showing popovers on restart though. 

0.0.26 was showing in installed community plugins - Obsidian 42 strange new worlds, the latest update wasn't.

So I uninstalled from the community plugin list and used BRAT to install again with:

TfTHacker/obsidian42-strange-new-worlds

On install, got the error message "BRAT This plugin is already in the list for Beta testing" 

Seems there's some code in there, not sure if it's just not getting fully uninstalled or what's happening.

Opened BRAT, Enable a plugin - toggle it on. Strange New Worlds isn't in the list to toggle on. 

0.0.27 now also now not in the list of installed community plugins.  

___ 
Things I've tried: 
Restarting device
Changing themes to see if css (Minimal) was obscuring the popovers, but with the default theme they aren't showing up for me either. 

I'm probably going to be leaving it on when on desktop, but mobile will leave it off so no worries on this. Happy to help any way if there's anything else you'd like me to check.

**Comment by TfTHacker** [comment]
Thank you for your detailed feedback, I really appreciate it. 

Can you do this for me? 
1. uninstall the plugin in the normal way (community plugins, uninstall)
2. Delete the plug-in in the list of plugins from within settings BRAT settings. 
3. And then try to reinstall it and see what happens.

I am thinking BRAT isn't updating right and is confused, so basically, remove the settings.

At the same time, I think mobile might have an issue.  will be testing this today.

**Comment by TfTHacker** [comment]
I made a quick video here. please see if this helps.

https://cln.sh/BxS444

**Comment by TfTHacker** [comment]
I think mobile support is now working properly, so I will close this out.

Tnx for the report!
