### ISSUE TITLE
add a reference count box for block references to callouts

### ISSUE THREAD

**Issue by kittenwhisky** [TfTHacker/obsidian42-strange-new-worlds#140]
Block references to callouts do not generate a reference count box in the source file.
It would be great to add the reference count box, similarly to block references to other types of content (Eg bullet points or headers).

**Comment by Hydro8** [comment]
Yes indeed it could be awesome to see files linked to a callout !
Exactly me need :)

**Comment by Hydro8** [comment]
Ok after some test I see the count box in edit mode when I'm in the callout but it disappear when the callout is render.

**Comment by TfTHacker** [comment]
I think this is now working, as I tested it in the most recent 2.2.0 release. If it isn't working for you, please provide me with a screenshot or sample file.
