### ISSUE TITLE
Heading references are not counted within the same file

### ISSUE THREAD

**Issue by cotneit** [TfTHacker/obsidian42-strange-new-worlds#142]
Just updated from 1.2.5 to 2.1.4, noticed that heading references within the same file are not counted. Heading references from other files seem to be counted fine, though I didn't do any thorough testing.

1.2.5
![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/36513243/e144fb94-a11e-4991-9308-55999326ada5)

2.1.4
![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/36513243/b10e2524-f5e6-492b-a245-bad372ea3a25)

**Comment by notuntoward** [comment]
I came here to report the same problem.

**Comment by TfTHacker** [comment]
This should now be addressed with update 2.2.0. Thank you for reporting this issue.
