### ISSUE TITLE
Cannot distinguish the title with the same name

### ISSUE THREAD

**Issue by jiajiala** [TfTHacker/obsidian42-strange-new-worlds#143]
![4](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/73203026/9ec025fa-f83b-403a-a3a9-d7a22a618dbc)
In the figure, all FFFF are considered to link to 11#ffff
This means that the title of the same name cannot appear in the same file, otherwise the BUG must appear

**Comment by TfTHacker** [comment]
This should now be addressed with update 2.2.0. Thank you for reporting this issue.
