### ISSUE TITLE
Links to the content within the same note do not display subscripts

### ISSUE THREAD

**Issue by zsygmmydnh** [TfTHacker/obsidian42-strange-new-worlds#145]
Note points to its own link, if the note name is not specified, such as [#heading ]] / [[#^ block - ref]], the corner mark will not be displayed.And explicitly write the note name [[my_note #heading ]] / [[ my_note #^ blkref]] so that there is a corner mark.
![image](https://github.com/user-attachments/assets/47588676-d6ab-4a2a-bcb4-60d1f46a8066)
![image](https://github.com/user-attachments/assets/c3d8b912-6ac2-40eb-a3d9-8543197933ba)

  Note points to its own link, the format is usually [#heading ]] / [[#^ block - ref]].The subscripts need to be displayed. Please solve this problem.

**Comment by jiajiala** [comment]
Hope you can fix this BUG, thanks

**Comment by TfTHacker** [comment]
This should now be addressed with update 2.2.0. Thank you for reporting this issue.
