### ISSUE TITLE
Support obsidian advance uri links

### ISSUE THREAD

**Issue by h4rsh-k** [TfTHacker/obsidian42-strange-new-worlds#147]
Is there any plan to support obsidian advance uri based links? 

Links of format `obsidian://adv-uri?vault=prep&uid=61d0c7b2-209a-4a14-bf58-258cd33abfa8`

**Comment by TfTHacker** [comment]
Thank you for your idea. No, there isn't a plan to add this since the internal API doesn't view this as an internal link even though it points to a vault.
