### ISSUE TITLE
Page total backlink count shouldn't include within-page links

### ISSUE THREAD

**Issue by notuntoward** [TfTHacker/obsidian42-strange-new-worlds#149]
If I create a link between from heading A to heading B on the same page, this increments the count of links for the total page.  It seems to me that what should happen instead is that the A --> B link should not increment the page count, but should increment the count of links to heading B

**Comment by greetclammy** [comment]
Agreed! The total note count should only show backlinks from other notes, and thus should mirror the *Linked mentions* count in the core Backlinks pane.

**Comment by TfTHacker** [comment]
Thank you for your feedback; it is much appreciated. I agree with you, but others consider a link a link, no matter where it is, so they want to see it in their workflow.

SNW isn't a replacement for the backlinks side pane, which gives you the view you are discussing, SNW compliments it.
