### ISSUE TITLE
Embed (transclusions) defects issue

### ISSUE THREAD

**Issue by nilssrvd** [TfTHacker/obsidian42-strange-new-worlds#15]
The plugin causes a problem with the alignment of the embeds (transclusions), moving them to the left as shown in the following image, and causing large squares to the right. This occurs with all three types of transclusions (![[Note]], ![[Note#Heading]], and ![[Note#^ID]]).

![Embed problem](https://user-images.githubusercontent.com/61798811/196930355-28fc5f3f-2c67-4f90-8cd6-78557b2777ce.png)

I have tested this issue on the Default Theme in addition to the one I am currently using. I don't know if the problem is caused by interaction with other plugins, but I have checked and it seems not; I preferred to report this here anyway, since it seems to me something important that may be of interest to you.

P.S.
Thank you very much for such a plugin! It is really fabulous and one of the most attractive features of Obsidian currently from my point of view.

**Comment by TfTHacker** [comment]
have you had a chance to troubleshoot this further? if you find more details, reopen this issue, and we can go further.
