### ISSUE TITLE
Should backlink counter show self-references?

### ISSUE THREAD

**Issue by greetclammy** [TfTHacker/obsidian42-strange-new-worlds#150]
Hey, I only discovered SNW today. While I'm excited to take advantage of its capabilities, I'm a bit confused: what's the point of showing a counter next to `Link A` if it displays *only* a single reference--the one it created itself? Furthermore, what's the point of displaying this info at all when you hover over the `Link A` counter, when `Link A` is... right there?

<img width="650" alt="Screen Shot 2024-10-27 at 17 18 09" src="https://github.com/user-attachments/assets/098aa128-a226-4017-abd1-9844f20120dd">

Is this intended or a bug? I don't think that a counter should show up next to `Link A` if the only reference that can be displayed is the one `Link A` created itself. 

I see that there's an `Minimum required count to show counter` option but that's beside the point because:
1. I want it to stay at 1 because I want to see all backlinks.
2. Regardless of what the setting is set to, this self-reference (which is redundant at best and distracting or misleading at worst) will still show up when you hover over the counter, even if nested among other backlinks.

**Comment by TfTHacker** [comment]
It is redundant, but there are also people who want to see self-references because of their workflows. On longer documents, this is also useful, as you see references from other places in the same document. So it's not a bug but by design. 

I appreciate your writing your viewpoint; keep it coming.

**Comment by greetclammy** [comment]
Thanks for explaining! I'm curious about the workflows where self-references are valuable - could you please share an example? Maybe it won't bug me as much if I know that it can be of use! 😅

Same-document references are useful indeed. Is this self-reference behavior primarily a byproduct of enabling that functionality, rather than a standalone feature? 🤔
