### ISSUE TITLE
Reference to Block ID from the same file doesn't work

### ISSUE THREAD

**Issue by charleshan** [TfTHacker/obsidian42-strange-new-worlds#153]
Reference to Block ID from the same file doesn't work. Seems to be related to #8.

Obsidian Version: 1.7.7
Strange New Worlds Version: 2.1.5

![ScreenCapture 2024-11-23 at 17 06 23@2x](https://github.com/user-attachments/assets/b05921c1-a78e-4b1b-94c8-4f7ae7ed7669)

**Comment by TfTHacker** [comment]
This should now be addressed with update 2.2.0. Thank you for reporting this issue.
