### ISSUE TITLE
Superscript font size

### ISSUE THREAD

**Issue by looneyapache** [TfTHacker/obsidian42-strange-new-worlds#16]
This plugin is fantastic. It's very helpful!  Thank you!
The only thing it could have used was a slightly larger superscript font size.

**Comment by TfTHacker** [comment]
Thanks for the feedback. Do you mean for the block count?

By the way, the block counts can also be overridden with custom CSS.

**Comment by looneyapache** [comment]
Indeed! It's the reference count please

**Comment by looneyapache** [comment]
Thank you!!! 🙇
