### ISSUE TITLE
[Bug] Weird interaction with other plugins when typing long bullet point

### ISSUE THREAD

**Issue by danieltomasz** [TfTHacker/obsidian42-strange-new-worlds#17]
Great idea and name for a plugin :) 

When typing long bullet points, they are  justified to the right, but when the Strange New Worlds is off there is no error anymore

I recorded the behaviour

https://www.loom.com/share/44f5a201980a4b5494c17a3de4fa2064

in the sandbox vault the typing is ok, I will investigate more
Plugin version 0.0.29, Obsidian 1.0.2
I have around 60+ plugins so it will take time to investigate. even with the Divide and conquer plugin

**Comment by TfTHacker** [comment]
Thank you for your detailed report, I really appreciate it. 

I was trying to duplicate this in my vault with no success, I have a bout 45 plug-ins. In addition, I opened a sandbox vault and was not able to reproduce it, so for sure, it's some conflict with some other plug-in. In general, though, the strange new worlds plug-in does not add any additional HTML to a block unless there is a link associated with something in the text. So it's unusual that SNW would actually affect the sample text I see you're typing here, as there are no links in the text.

**Comment by danieltomasz** [comment]
Ok, I can replicate it in the Vanilla Vault with only a few plugin enabled; 
To reproduce text must be typed in the subbullet, not the one on the highest level

**Comment by TfTHacker** [comment]
I am happy the bug is not with me :-) but interesting catch on your part!

**Comment by danieltomasz** [comment]
I catched it when I was debugging another  plugin when producing MVE :)
