### ISSUE TITLE
[UI/UX] Better sidebar text alignment when empty

### ISSUE THREAD

**Issue by danieltomasz** [TfTHacker/obsidian42-strange-new-worlds#21]
Currently the text don't have borders around it, it is also white (the theme is minimal, but what I would want is to use the second "dimmed" variable for colors as most plugins use instead of primary color)

<img width="348" alt="image" src="https://user-images.githubusercontent.com/7980381/197422198-34148f66-82db-457f-88ea-eb0fd60a8317.png">

Example improvement how the text might looks like (Pandoc References Plugin)
<img width="346" alt="image" src="https://user-images.githubusercontent.com/7980381/197422172-69c6d7c8-ac75-4931-a2c3-f9e99ae8eaec.png">

**Comment by TfTHacker** [comment]
Very nice idea, tnx. This will rollout with the 0.0.30 update today.

Also the text in the pane can be overridden with the following CSS elements:

snw-sidepane-loading
