### ISSUE TITLE
Separate window support — ? — Modal appears behind window

### ISSUE THREAD

**Issue by bwydoogh** [TfTHacker/obsidian42-strange-new-worlds#24]
Triggering the modal on a new window -> it appears behind that window.

See the attached screenshot.

I am using the default theme.

![screenshot_20221028 _093339](https://user-images.githubusercontent.com/1235571/198530840-84c32150-4be6-4ed1-980f-61630096ffe8.png)

**Comment by TfTHacker** [comment]
Thank you for reporting this. I have to admit, support for new window was not working for many things. So good report and hopefully I caught all issues.

**Comment by bwydoogh** [comment]
Thanks! Working fine now.
