### ISSUE TITLE
Headings counter button don't work when adding tag 

### ISSUE THREAD

**Issue by madaolee** [TfTHacker/obsidian42-strange-new-worlds#25]
unexpected issues: After adding tags after the title, the Headings counter button don't show.

![image](https://user-images.githubusercontent.com/72607182/198792423-bc2debab-9612-4f94-9ff0-8d178f1ac01e.png)

![image](https://user-images.githubusercontent.com/72607182/198792322-58153f6f-9791-4c9c-b1be-ef1a807c7b18.png)

**Comment by TfTHacker** [comment]
Thank you for reporting this. I fixed it.

And since I have no place to get therapy, let me just say I hate fixing bugs in the headers 😸

**Comment by madaolee** [comment]
Thanks a lot !
