### ISSUE TITLE
errors in console

### ISSUE THREAD

**Issue by derekvan** [TfTHacker/obsidian42-strange-new-worlds#27]
Had the console open to debug a script and I saw many repeated errors from strange new worlds, would throw every time a new file opened.

<img width="475" alt="Screen Shot 2022-10-31 at 9 52 26 PM" src="https://user-images.githubusercontent.com/890341/199141579-08b05d17-c8b0-462d-b336-21485b5ae7d2.png">

**Comment by TfTHacker** [comment]
Thank you for reporting this. I believe I have resolved this and will be pushed out with SNW 1.0.3 (today).
