### ISSUE TITLE
Feature request | Simple to install zip file in release and/or adding it to the community plugins list in Obsidian

### ISSUE THREAD

**Issue by SebbeJohansson** [TfTHacker/obsidian42-strange-new-worlds#30]
Hi! Adding a zip file in the release to more easily extract the contents directly into the correct place would be great.
Even better would be if the plugin was in the community plugins list in Obsidian!

**Comment by TfTHacker** [comment]
I have submitted the plugin. Hopefully it will be approved here shortly.

This plugin can also be very easily installed with the BRAT plugin.

**Comment by SebbeJohansson** [comment]
Interesting! I have never heard of "BRAT. I will check it out asap :)
