### ISSUE TITLE
Cannot click on the beginning of each line when splitting

### ISSUE THREAD

**Issue by madaolee** [TfTHacker/obsidian42-strange-new-worlds#31]
the latest version（1.0.3）

 I found that I could not click to select the beginning of each line  when splitting left and right

https://user-images.githubusercontent.com/72607182/199883169-511c24b0-24bb-4314-bfe1-eccfb940a2fb.mp4

**Comment by TfTHacker** [comment]
Thank you for your report. If you turn off SNW this works well? It seems you are using the outliner plugin?

The video doesn't really show me where SNW is causing an issue, so please give me a few more details.

**Comment by madaolee** [comment]
> 

Yes, when I turn off SNW it works well. and this issue came up after I updated SNW this morning. And I've tried using the default topic and then just turning on SNW, and the problem still exists, so I feel like this should be a problem caused by SNW.

Here is a more detailed video, my English is not very good, I do not know if it is expressed clearly, please forgive me.
https://user-images.githubusercontent.com/72607182/199893530-45c6a1f6-cd0b-4fcf-9ed3-c95c841e4a7a.mp4

**Comment by madaolee** [comment]
Yes, when I turn off SNW it works well. and this issue came up after I updated SNW this morning. And I've tried using the default topic and then just turning on SNW, and the problem still exists, so I feel like this should be a problem caused by SNW.

Here is a more detailed video, my English is not very good, I do not know if it is expressed clearly, please forgive me.


https://user-images.githubusercontent.com/72607182/199894240-0f926afd-a526-4867-941f-f544bef5dab3.mp4

**Comment by TfTHacker** [comment]
Your english is just fine! You nicely explained the issue. I am not able to reproduce it, but I am going to try today and this weekend to see if I can.

**Comment by madaolee** [comment]
Thanks a lot!

**Comment by TfTHacker** [comment]
I am curious if you have these settings on:

<img width="791" alt="CleanShot 2022-11-08 at 05 25 24@2x" src="https://user-images.githubusercontent.com/69121180/200474931-f6f28154-2e5d-4d39-8226-021c20b6b439.png">

If so, if you turn them off do they fix the issue?

**Comment by madaolee** [comment]
Turning off these options does not fix the issue.
Beside,I can reproduce the issue in sandbox and my friend's computer.
This is a really confusing bug.

**Comment by TfTHacker** [comment]
So try this please. Turn off gutters.

![CleanShot 2022-11-08 at 06 48 52](https://user-images.githubusercontent.com/69121180/200485230-afae5623-d40f-469d-96b7-022a31136772.png)

**Comment by madaolee** [comment]
Now it's solved, thank you sincerely for your patient response

**Comment by TfTHacker** [comment]
well, that is still a bug. I will have to figure out why the gutter caused that. Another test you can try is turning the line number on in the editor (which is a gutter as well) and seeing if you experience the same issue.

The question is: is this an SNW bug, or something to do with gutters in general?

![CleanShot 2022-11-08 at 07 12 51](https://user-images.githubusercontent.com/69121180/200488749-7ceae21a-d8d7-4a2d-8bfd-4255898068de.png)

**Comment by madaolee** [comment]
If I turn on _Show line number_, everything is ok. And I can also turn on _Embed references in Gutter in Live Preview Mode (Desktop)_, the issue is fixed.

**Comment by madaolee** [comment]
https://user-images.githubusercontent.com/72607182/200493206-ac2054bf-d422-45a5-a98d-730b38619c5a.mp4

**Comment by TfTHacker** [comment]
I have closed this because in the end it wasn't a bug. Obsidian creates a gutter margin in various scenarios, for example when showing line numbers in the editor. SNW uses "gutters" in some cases. This is off by default in settings. If it gets turned on a gutter is added for SNW.

Each them handles gutters differently. So try different themes to find something that works well for SNW.
