### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by looneyapache** [TfTHacker/obsidian42-strange-new-worlds#34]
Hi,

I'm sorry to bother you again, but I seem to have a strange problem.

I am curious if SNW matches are case sensitive. 

In my case SNW works only if cases are same else count is inconsistent.

Please verify 

![Obsidian_mbQdYsC19H](https://user-images.githubusercontent.com/10562851/200101857-ed9d147e-bc52-47b3-b404-0a265f044f08.gif)

**Comment by looneyapache** [comment]
Furthermore, there is just one note with the term "Expenses" in the entire vault, ruling out race/conflict in the count.

**Comment by TfTHacker** [comment]
No worries. I was able to reproduce the bug and will troubleshoot here soon. Today pushed out a big internal update so now can get to some bugs.

**Comment by looneyapache** [comment]
Thank you, I appreciate your help! :)

**Comment by TfTHacker** [comment]
ohhh i spent a lot of time on this, but I think with the upcoming 1.2.0 update this will be fixed. Please try in a few days and if you have issues, please let me know.

**Comment by looneyapache** [comment]
Thank you!!!
