### ISSUE TITLE
Scalability for iOS - memory protection 

### ISSUE THREAD

**Issue by Oblique82** [TfTHacker/obsidian42-strange-new-worlds#35]
Firstly I really love this project

I just wonder if possible to have some memory safeguards for the ambitious crowd

those who work with large interconnected collections of notes with scripture that link to lexicons, dictionaries or word definitions. I have 20 k notes and some of these are generating 7000+ results in the SNW links which crash my iPhone if I click them (memory issues I assume)

I realise this is extreme but I am just thinking in terms of scalability

a simple option like - "limit to N results" would help eg limit to 30 results so I don't accidentally crash my vault

see attached screenshot :)
![Screenshot 2022-11-06 at 9 09 47 pm png](https://user-images.githubusercontent.com/98437638/200166539-1041fbcf-c30a-404d-9bd4-f5452ab3d5e1.png)

**Comment by TfTHacker** [comment]
I am glad you reported this. I saw it as well. I will probably do something like return the count, but when you click on the count it will only show something like 30 or so file references. I will set this up to be configurable.

Thank you for reporting this.

**Comment by Oblique82** [comment]
Yes, I was thinking that too

**Comment by TfTHacker** [comment]
This was fixed a while back, I forgot to say something. It is the maximum number of files to show setting.
