### ISSUE TITLE
[FR] Block indexing by path

### ISSUE THREAD

**Issue by bramses** [TfTHacker/obsidian42-strange-new-worlds#36]
It would be awesome if there was a way to skip indexing certain directories all together -- an option perhaps similar to the way Templater does things?

![Screenshot 2022-11-06 14-51-54](https://user-images.githubusercontent.com/3282661/200194524-6d612f1a-f5f6-4b29-a9c9-1c0442761393.png)

Thank you for your work on this great plugin!

**Comment by TfTHacker** [comment]
Excellent idea and I am kicking this one around in my mind. Just curious, what is your scenario? what kind of things would you exclude?

**Comment by bramses** [comment]
@TfTHacker My scenario is a bit unique 😅 . I wrote a Chrome extension that converts history into an advanced MD table in Obsidian and links the day. So I've seen a lot of SNW's reach well into the 100s depending on the links I visited that day (see below for example). Ideally, I'd like to stop indexing `History/` all together 


![Screenshot 2022-11-07 17-36-03](https://user-images.githubusercontent.com/3282661/200438338-bb234dc9-f19f-4b7c-a81f-f8290dc9df36.png)
