### ISSUE TITLE
Linking in heading leads to wrong indicator

### ISSUE THREAD

**Issue by tim-hilde** [TfTHacker/obsidian42-strange-new-worlds#37]
I have disabled the indicator for links like `[[note]]`. For headings I have it turned on. If I then link to a note inside a heading as in `# this is a [[note]]` the indicator shows the number of links to that note despite being turned off and not the number of links to the heading itself:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/44113468/200565068-2f0ad822-cfeb-4a94-a0f7-6c2bcfb841a7.png">

**Comment by TfTHacker** [comment]
I think this will be fixed with 1.2.0. Please test in a few days and if there is still and issue, reopen this issue with more details.

**Comment by tim-hilde** [comment]
This is still happening in 1.2.0

**Comment by TfTHacker** [comment]
Ok. I think I found the issue. Pushing out shortly 1.2.1. Let me know again if it isn't resolved :-)
