### ISSUE TITLE
Popover from Header Counter Unreadable

### ISSUE THREAD

**Issue by chrisgrieser** [TfTHacker/obsidian42-strange-new-worlds#38]
Hovering the counter in the header (great idea, btw!) leads to an unreadable popover, since it is displayed above the counter and cut off there (tested in default theme)
<img width="476" alt="Pasted image 2022-11-09 21 01 51" src="https://user-images.githubusercontent.com/73286100/200929739-cc5f7356-42f6-46b1-8296-ef8e2f5adb59.png">

I think displaying the popover below the counter could fix this? 🤔

**Comment by TfTHacker** [comment]
Yes I have seen this as well a few times, so thank you for reporting it. was this on desktop or mobile?

I just pushed out a 1.0.6 update where I change the positioning strategy. I think it will fix this problem and in fact positions the popup better.

Its still a bit flaky on mobile, but I will tweak that at a future time.

**Comment by chrisgrieser** [comment]
Was on desktop. Die not occur anymore, thanks!
