### ISSUE TITLE
Indicators don't appear correctly on tasks as well 

### ISSUE THREAD

**Issue by vkbytes** [TfTHacker/obsidian42-strange-new-worlds#39]
The indicators are shown twice on tasks or on checkboxes if there's a file with a task with links, this also miss matches the indents

![CleanShot 2022-11-08 at 20 05 14](https://user-images.githubusercontent.com/79217316/200593456-94dc74a6-8e11-4ebc-8df1-c69a6338e08d.png)

**Comment by kandyman2017** [comment]
I have this issue with the Red Graphite theme:

![edit](https://user-images.githubusercontent.com/32620963/218307090-319a35ec-894a-4a70-a5a7-9fb1d78c84ed.jpg)
![preview](https://user-images.githubusercontent.com/32620963/218307096-a85e7dad-7ccb-4873-8428-bf0ae44236b4.jpg)

**Comment by dipsy** [comment]
same issue with minimal theme

**Comment by TfTHacker** [comment]
I think this issue is resolved with some recent updates. Wait for 1.2.0 and see if the issue goes away.

If you see the issue still, please create a new vault and do some testing with the theme and SNW. Sometimes other plugins CSS can interfere. So it would be good to know if here is a conflict.
