### ISSUE TITLE
Possible conflict with the Kanban plugin

### ISSUE THREAD

**Issue by wenlzhang** [TfTHacker/obsidian42-strange-new-worlds#4]
I am using this plugin version 0.0.04, Kanban version 1.3.17 and Obsidian version 0.16.2. Once I switch a Kanban note to Markdown mode and then back to Kanban mode, all embedded notes would not render. For example, `- [ ] ![[Note#^blockID]]` would just display as it is, instead of the rendered embed results.

Also, I see the following messages in the console:

```
plugin:obsidian42-strange-new-worlds:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'lineEnd')
    at I (plugin:obsidian42-strange-new-worlds:1:4645)
    at eval (plugin:obsidian42-strange-new-worlds:8:482)
    at Function.<anonymous> (app.js:1:1204656)
    at app.js:1:235237
    at Object.next (app.js:1:235342)
    at app.js:1:234279
    at new Promise (<anonymous>)
    at m (app.js:1:234024)
    at Function.t.renderMarkdown (app.js:1:1204268)
    at Object.eval [as __] (plugin:dataview:15997:35)
25plugin:obsidian-kanban:62 TypeError: Cannot read properties of null (reading 'lineEnd')
    at I (plugin:obsidian42-strange-new-worlds:1:4645)
    at eval (plugin:obsidian42-strange-new-worlds:8:482)
    at Function.<anonymous> (app.js:1:1204656)
    at app.js:1:235237
    at Object.next (app.js:1:235342)
    at app.js:1:234279
    at new Promise (<anonymous>)
    at m (app.js:1:234024)
    at Function.t.renderMarkdown (app.js:1:1204268)
    at ba (plugin:obsidian-kanban:62:6178)
```

**Comment by TfTHacker** [comment]
Thank you for reporting this. I assume you were using 0.0.0.1 of SNW without an issue with these plugins.

Will try to get a fix out ASAP.

**Comment by TfTHacker** [comment]
I have pushed out 0.0.05 to address this issue. Basically, for now I have to turn off SNW inside their rendering view. The way the Kanban plugin handles click events, overrides all the internal content. So, for now I am not sure how to override this.

But it seems SNW and Kanban don't need to be integrated. What do you think?

**Comment by wenlzhang** [comment]
Thanks for the quick fix!

> But it seems SNW and Kanban don't need to be integrated. What do you think?

I don't think SNW needs to be integrated with Kanban mode, either. For me, Kanban mode is mainly used as a way of arranging/linking tasks/notes. In such a use case, seeing the connections provided by SNW is not a priority. If one needs to achieve this, one can switch to Markdown mode instead.

**Comment by TfTHacker** [comment]
Ok, this is what I thought as well. Thanks for the confirmation and sorry for the issue. I am now working on SNW, so submit bugs and suggestions. 

Currently focus on improving the accuracy of the "count" in documents and using the side pane to have more useful info.
