### ISSUE TITLE
Add support for footnotes

### ISSUE THREAD

**Issue by Trikzon** [TfTHacker/obsidian42-strange-new-worlds#40]
Hi, I'm just now trying out the plugin and am enjoying it so far.

However, I use footnotes *a lot* in my notes and it seems that they aren't properly supported.

## If a link is referenced in a footnote then it doesn't display the Strange New Worlds reference count in Live Preview mode

Live Preview:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/29845000/201257052-fc415101-5642-49ab-88a2-bec2e5250e4d.png">

Reading:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/29845000/201257075-33d4a771-413e-43ac-bfb3-6c05a3386ca8.png">

## With the same link, if I click on the reference count then the preview of where it's used is blank
<img width="292" alt="image" src="https://user-images.githubusercontent.com/29845000/201257210-2d0274c4-ac84-461a-9f7d-5da8418092c6.png">

Hope that this helps and that there are plans to add footnote support. Thank you :)

**Comment by TfTHacker** [comment]
This will be addressed in the upcoming release. Thank you for bringing it to our attention, and we apologize for the delay in resolving it.
