### ISSUE TITLE
Feature request: Ignore notes

### ISSUE THREAD

**Issue by reddare** [TfTHacker/obsidian42-strange-new-worlds#41]
Hi! It would be great to be able to exclude some notes from the list of backlinks.
For example, similar functionality is available in the Influx plugin and it is very convenient.
Thank you!

**Comment by TfTHacker** [comment]
We are planning to add a "Exclude" folder feature soon. In the mean time, you can do per document exclusion. Check out the docs here:

https://github.com/TfTHacker/obsidian42-strange-new-worlds#snw-frontmatter-directives
