### ISSUE TITLE
Unique Icon

### ISSUE THREAD

**Issue by ryanwwest** [TfTHacker/obsidian42-strange-new-worlds#42]
SNW has the same side pane icon as the default local graph view, adding some guesswork when trying to quickly jump to one or the other:

![Screen Shot 2022-11-15 at 09 10 48](https://user-images.githubusercontent.com/31378238/201940450-1a367a86-464d-46b4-a68b-bc769ff89535.jpg)

Could we perhaps swap it out for a unique icon for SNW?

**Comment by TfTHacker** [comment]
Oh yeah, this is not good. I don't use graph currently. Thanks for pointing this out.

Fixing here in a few minutes.
