### ISSUE TITLE
Place reference above or after any commas, periods or other punctuation marks

### ISSUE THREAD

**Issue by kenanmike** [TfTHacker/obsidian42-strange-new-worlds#44]
Thanks for this fantastic (+ beautiful) plugin. I love it!
I was just wondering whether references could be made to look more natural when accompanied with punctuation, such as by making the reference appear directly above the punctuation or immediately afteer that. As you can see they currently add a big gap between the punctuation which looks awkward. Usually in academic work, for example, footnotes are placed after any punctuation because they look better. 
<img width="232" alt="Screenshot 2022-11-15 at 21 39 52" src="https://user-images.githubusercontent.com/85374001/202000041-4a3b7537-bb46-4079-b94c-43a34ba17dab.png">
<img width="233" alt="Screenshot 2022-11-15 at 21 40 09" src="https://user-images.githubusercontent.com/85374001/202000049-35856d19-f74b-4f19-a4c3-9cefb9ffd7a3.png">

**Comment by TfTHacker** [comment]
Basically SNW is detecting the location of links and doesn't analyze the surrounding text. Too much of a performance hit. If you now CSS thought, these elements can be moved around with experimentation.

**Comment by tophee** [comment]
I also love the plugin and support this suggestion/ feature request.

> Too much of a performance hit. 

Assuming that this is about regular expressions, does it really make much of a difference whether you do 
~~~regexp
\[\[.*\]\]
~~~

or something like
~~~regexp
\[\[.*\]\]\S?\S?
~~~
?

**Comment by TfTHacker** [comment]
Thank you for this recommendation, but I will not be implementing it. The parser and UI layouts are complex and challenging to manage in terms of performance. Alternatively, you could put together some CSS that repositions the block counter to float above the link, or another adjustment you would prefer.

Again, I do appreciate the recommendation.
