### ISSUE TITLE
Style bug

### ISSUE THREAD

**Issue by Quorafind** [TfTHacker/obsidian42-strange-new-worlds#47]
![image](https://user-images.githubusercontent.com/13215013/202068115-ee6cf2b8-b009-4060-8bbe-b73282908778.png)

When using the Hover editor, the generated tippy div is partially obscured by hover editor's default header.

If it is possible to make the tippy over the body?

**Comment by TfTHacker** [comment]
Would please do a loom so I can more clearly see what you are referring too?

**Comment by Quorafind** [comment]
Sure, here it is :
https://user-images.githubusercontent.com/13215013/202085576-c2358e97-a9f0-47bf-8890-2ca2566932b4.mp4

**Comment by TfTHacker** [comment]
Ok. Thank you. What version of SNW are you on?

**Comment by Quorafind** [comment]
😢 so sorry that I found I didn't update to the latest version, I updated and now it works correctly. @TfTHacker

**Comment by TfTHacker** [comment]
No problem, I am glad this is fixed. I thought I recently fixed it 😄 . Keep the reports coming if you have issues.
