### ISSUE TITLE
cannot read properties of undefined (reading 'excludedFile')

### ISSUE THREAD

**Issue by zsviczian** [TfTHacker/obsidian42-strange-new-worlds#48]
I can't see a negative effect of this error, just spotted it in developer console and thought to share it...

![image](https://user-images.githubusercontent.com/14358394/202378702-8008f1dd-c6fc-456a-8410-8e8ee25ee768.png)

**Comment by TfTHacker** [comment]
Thank you for reporting. I don't like unresolved console errors :-)

Will address this in a day or two.

**Comment by TfTHacker** [comment]
@zsviczian I was not able to reproduce the error, but its clear to me where it might be coming from. Please let me know after updating to 1.0.9 if the error still occurs. I have a few more things I can do if it does.
