### ISSUE TITLE
Reference count for individual headings

### ISSUE THREAD

**Issue by kaufman79** [TfTHacker/obsidian42-strange-new-worlds#5]
I am loving the plugin so far, but it is missing a feature I would consider to be vital -- to show the number of references to individual headings. I can see which headings are linked to in the sidepane, but not in order, and I see all of them, not just links to an individual heading. I can reference that heading somewhere else other than the heading to see the number, which is a cumbersome workaround for now.

This is something Block reference counter does/did, but it is no longer supported and has many issues.

**Comment by TfTHacker** [comment]
Thank you for the feedback. Can you explain again what you asking? I say this because I think this is supported already. You should see next to a heading how many references there are to it. So I am missing something :-(

**Comment by kaufman79** [comment]
Oh okay, yes I do not see that number. Nothing in the settings is helping. I just found out that I do see the number if I embed that note elsewhere -- I can see the number and click on it in the embed.

**Comment by TfTHacker** [comment]
Can you do a Loom video showing me?

**Comment by kaufman79** [comment]
Actually, just got it to work! Restarted pc and checked (had not restarted PC since downloading Obsidian 16 and BRAT and SNW) and no fix initially. Then toggled "enable reference types (headers) in live preview mode" off and on and reloaded the notes and it works. Very excited about the full functionality!
