### ISSUE TITLE
Feature request: Make keywords more visible in results pane

### ISSUE THREAD

**Issue by ryadaj** [TfTHacker/obsidian42-strange-new-worlds#50]
I tried this on default theme and it is _slightly_ better, but if the linked word/phrase in the results pane could be given more contrast than present, either via darker bolding or a highlight, that could be helpful. 

Not sure if possible, but just wanted to put it out there 🫠

<img width="1912" alt="Screenshot 2022-11-18 at 08 18 17" src="https://user-images.githubusercontent.com/82765301/202714536-a4c45a9c-c69f-4519-b179-7ee07529870c.png">

**Comment by TfTHacker** [comment]
Thank you for reaching out with this idea. SNW in the file preview is using default styling for the pane from search. What this means is its using the themes default as defined for search results. So you can tweek these settings with CSS.

**Comment by ryadaj** [comment]
Oh that's good to know! I'm not very technical so I'll have to ask around for some help with that :)

**Comment by theowoo** [comment]
> Thank you for reaching out with this idea. SNW in the file preview is using default styling for the pane from search. What this means is its using the themes default as defined for search results. So you can tweek these settings with CSS.

@TfTHacker Thanks for creating this plugin. I don't think the current version respects the default styling from search. Demo:

![snw_links](https://user-images.githubusercontent.com/9566341/221608365-eeeb252c-2a64-453c-b466-7b229818b0c9.png)

1. Built-in search: highlight
2. Built-in backlinks ("toggle backlinks in document"): highlight
3. SNW panel: normal

___

I have been able to tweak the behaviour somewhat using the following CSS snippet, but it would highlight all links in the search context, not just the relevant link. 

```
.snw-ref-item-info a {
    text-decoration: underline; 
    /* color: var(--link-color) !important; */
    background-color: var(--text-highlight-bg);
}
```

Is there a way to selectively restyle links to the node under inspection? Thank you.
