### ISSUE TITLE
Option to display linked mentions only

### ISSUE THREAD

**Issue by mjknght** [TfTHacker/obsidian42-strange-new-worlds#51]
Hello! This is a brilliant plugin – didn't know I needed it; adds a whole dimension now that I have it.

I notice that the count displays both linked mentions and unlinked mentions. I am assuming that behaviour is as intended, but I'd quite like to be able to only display a count and preview for linked mentions, since I'd rather just see explicit connections I have made. Perhaps I am the only one, but if I'm not, could that be considered as a feature request?

Thanks once again!

**Comment by TfTHacker** [comment]
Thanks for writing. Actually the plugin should only report real links as Obsidian sees them. It doesn't process unlinked mentions.

I am curious if something else is showing up in your vault that this plugin is misinterpreting.

**Comment by TfTHacker** [comment]
No bother at all. this is a new tool and needs to be scrutinized until we are sure its accurately reporting numbers. so please keep the feedback coming 👍
