### ISSUE TITLE
[Feature Request] Min and Max reference count in settings as a text field

### ISSUE THREAD

**Issue by Glint-Eye** [TfTHacker/obsidian42-strange-new-worlds#53]
Right now the entry for "Minimal required count to show counter" and "Maximum file references to show" are a small slider which makes it impossible to select values like "2", which I wanted to do for "minimal count". I'd suggest turning it into a text entry field.

Cheers and great plugin :)

**Comment by TfTHacker** [comment]
I agree with you. This slider control in Obsidian isn't ideal. I will change this to a number input to make it easier.

Until I get to it, if you click once on the slider, then you can use your arrow keys to left and right to change the setting value

**Comment by j-maffe** [comment]
I wanted to submit an enhancement just like this. Maybe until you make the change put that tip about the arrow keys?
