### ISSUE TITLE
Counter in PDF Export

### ISSUE THREAD

**Issue by stefanopagliari** [TfTHacker/obsidian42-strange-new-worlds#54]
This is a small issue but I noticed that the link counter appears when I export a note as a pdf. Temporarily de-activating the plugin solves the issue but my impression is that the default should be to hide the reference counter when exporting a note if possible.

**Comment by TfTHacker** [comment]
Thanks for submitting this. I won't get to it right away but I will see if I an find a solution.

**Comment by TfTHacker** [comment]
So I have looked at this closer and didn't find a solution. However, you can toggle the plugin off using command palette quickly and turn it back on:

<img width="735" alt="CleanShot 2023-05-14 at 16 19 17@2x" src="https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/69121180/b6cb4af5-6604-48fa-b780-12ab8e676cda">

The key is to toggle off the plugin with this command and likely close/reopen the document and there should be now block ref counters.

Another option is the block reference counters are HTML. you could create a custom CSS to make them hidden, and control that with frontmatter or toggling on/off CSS in appearance settings.
