### ISSUE TITLE
Uninstalling leaves files back and shows an error

### ISSUE THREAD

**Issue by merlinuwe** [TfTHacker/obsidian42-strange-new-worlds#57]
Uninstalling the plugin leaves these files back:

![image](https://user-images.githubusercontent.com/4138869/204104252-f5d67d61-5aea-4883-884c-b34179ac35e7.png)

This leads into this error message:

![image](https://user-images.githubusercontent.com/4138869/204104298-09f7dccf-f80c-4855-bbe3-d6a8c3ec3322.png)

Deleting the folder with these 3 files doesn't resolve the problem. What can I do?

**Comment by TfTHacker** [comment]
Sorry that happened. I think in this case, Obsidian just didn't properly delete the files.
