### ISSUE TITLE
Open in active note instead of sidebar

### ISSUE THREAD

**Issue by ryanwwest** [TfTHacker/obsidian42-strange-new-worlds#6]
I see that you take inspiration from https://github.com/shabegom/obsidian-reference-count and appreciate your efforts to continue it. One thing that I love from that plugin is how when you click a reference number count, it opens a dropdown immediately below the reference without otherwise disrupting the note.

In this plugin, when I click the corresponding reference number count, it always opens in the _right_ sidebar (even if I try to move that mini-pane to the left sidebar, it switches back). This is problematic as I only use the left one and have my Obsidian window open just wide enough to have the left sidebar always open and have the full width of the active pane text. When I click something, it auto-opens the right sidebar which cramps up the spacing in the main pane.

I see some documentation about shortcuts like alt-click to open a horizontal sidebar, but haven't gotten any of those to work. However, I would most prefer to just be able to open it in the active pane similar to the other plugin's behavior (or have an option to enable this in the config).

**Comment by TfTHacker** [comment]
Thank you for testing the plugin and taking the time to write. I agree with all you said. In the last week I have done major updates.

First if you hover over the block reference count, it will show a hover popup of all related references. This list is scrollable. 

If you click on the counter, it will open the same list with previews in the side pane. You can use the hover editor plugin to get previews and also edit the content.

DM me on Discord or Twitter and can send you some private videos of how this works.

Unfortunately implementing the roam strategy for now is maybe not possible (or beyond my ability).

**Comment by ryanwwest** [comment]
Thanks. I haven't figured out how to get hovering to enable a scrollable list of related references yet. Are the list elements supposed to be clickable? I'm happy to DM you though it may be worth putting instructions here for public discoverability. 

Is the 'roam strategy' you mention the same as https://github.com/shabegom/obsidian-reference-count where the references open in the active pane in live preview mode? I wonder how that plugin implemented it but understand if that isn't a priority.

But if not, I would really appreciate at least being able to have it open on the left side pane instead of the right; it still insists on opening on only the right side even after I move the 'Strange New Worlds' pane icon.
