### ISSUE TITLE
The left margin increased

### ISSUE THREAD

**Issue by Missionary2112** [TfTHacker/obsidian42-strange-new-worlds#62]
- After the plugin enabled, the left margin increased
![2022-12-09_02 41 45_CSX](https://user-images.githubusercontent.com/98799613/206684824-74773a8c-8400-442c-8e8e-ac91f1404ada.jpg)

- After the plugin disabled, the left margin goes back to normal
![2022-12-09_02 42 31_CSX](https://user-images.githubusercontent.com/98799613/206684848-0b9c8d7d-55c9-43a2-95a6-7eca5c01811d.jpg)

**Comment by TfTHacker** [comment]
Thanks for contacting us. SNW uses a gutter for displaying block refs in some scenarios. Some themes make large gaps for the gutters. You can often see this if you turn on line numbers.

Option 1 is to use another theme (minimal works well)

Option 2, You can disable gutters in settings:

![CleanShot 2022-12-16 at 13 10 04](https://user-images.githubusercontent.com/69121180/208095294-3cc3c419-4fbd-46ab-9ca0-47c7cd3dbda7.png)
