### ISSUE TITLE
[Feature request] hiding numbers 

### ISSUE THREAD

**Issue by joniac1** [TfTHacker/obsidian42-strange-new-worlds#63]
Hi, thanks for your contribution to the obsidian community. 

It would be great to be able to hide the numbers above links. It could facilitate the reading process without losing the plugin experience. 

Regards,

Joniac

**Comment by TfTHacker** [comment]
Tnx for your feedback. What would you suggest? some kind of small visual indicator in place of the number?

FYI: you can use command pallette to temporarily toggle of SNW.

**Comment by joniac1** [comment]
Sorry, I was not really clear, Yes I effectively suggest a small visual indicator in place of the number.

**Comment by chiusuan** [comment]
> Sorry, I was not really clear, Yes I effectively suggest a small visual indicator in place of the number. 

I want to hide the dashed boxes and keep the numbers. It would be even better if you could customize the border shape, background color, and font color of the numbers.

**Comment by TfTHacker** [comment]
Please check this out for how to customize: 

https://github.com/TfTHacker/obsidian42-strange-new-worlds/discussions/19
