### ISSUE TITLE
Question: What is a ghost link?

### ISSUE THREAD

**Issue by Liong1976** [TfTHacker/obsidian42-strange-new-worlds#67]
Hi there,

First, I would like to express gratitude for making this awesome plugin.

You mentioned that the newest update comes with a feature to link to a document that doesn't exist.  What does it mean? Can you explain a bit about that? Is that a link to unresolved links? If so, I would benefit from this new feature because I use many unresolved links to build my MOC instead of using tags.

**Comment by TfTHacker** [comment]
It is a term another used, so not sure if its a proper term. but the idea is as follows: Let's say you are editing a document and you insert a link to a document that doesn't exist, it is a ghost link. The link exists in your document, but the actual document that you are intending to link to doesn't exist until you create it, or click on the link.

Some users use these ghostlinks just to create a connection, even though it doesn't connect to anything real. I think the graph can show these types of "pseudo" connections. We are trying to get SNW to respect this.

Hope that helps. Please mark as complete if it makes sense.

**Comment by Liong1976** [comment]
Hi @TfTHacker,

Thanks for the explanation. I have a lot of pseudo/ghost links in my vault, but I don't see the new feature works in my side. How to activate that feature?

**Comment by TfTHacker** [comment]
No you don't have to turn it on. But as I said, its experimental. Can you demonstrate the links not showing up?

**Comment by Liong1976** [comment]
Sure.

In both notes, Dummy Text and Dummy Text Copy, I wrote a ghost link, `[[Dummy Text Link]]`.  There is no notification in both notes in the **LP**, as you see in the screenshots below.

![image](https://user-images.githubusercontent.com/88898230/208325373-d60a8095-edca-4931-8bcf-ccc4102e1415.png)

![image](https://user-images.githubusercontent.com/88898230/208325393-49b0d225-8ba3-4faa-8927-48febe72a7eb.png)


However, I saw the links in the **Reading Mode**. Is that what you intended, that the links can only be seen in the Reading Mode?

![image](https://user-images.githubusercontent.com/88898230/208325445-62310913-baf2-496d-ac45-85c91aafa184.png)

![image](https://user-images.githubusercontent.com/88898230/208325476-1753ea7b-0820-43ec-89f7-ef8ffccb4e61.png)

**Comment by wannli** [comment]
Same here. Only in reading mode. May we expect that it will start working in editing mode at one point, as well? Great feature! 👍

**Comment by TfTHacker** [comment]
Ok, I think in the upcoming 1.2.0 update this is fixed. Please give it a try once 1.2.0 is out and report back if you have issues.

**Comment by Liong1976** [comment]
Thanks, @TfTHacker

Looking forward to the update
