### ISSUE TITLE
[Feature Request] Option to exclude or include pages based on dataview query

### ISSUE THREAD

**Issue by Marco-Pozzecco** [TfTHacker/obsidian42-strange-new-worlds#72]
I made this feature request for the necessity that each user has to personalize their workflows. In my personal case, I have some notes, which can be classified as structural notes, that don´t  provide any value. For this reason I'd like to exclude them.
I believe there are other people with the same problem as mine.

If this request doesn't conflict with your long term view than I would like to offer my help.

**Comment by TfTHacker** [comment]
Thank you for writing, SNW does support the ability to exclude files, just not on a dataview query. It s a cool idea, but could possibly be a performance issue since we are constantly querying already.
