### ISSUE TITLE
When I use Chinese input method, the numbers disappear

### ISSUE THREAD

**Issue by doit132** [TfTHacker/obsidian42-strange-new-worlds#73]
## 动画演示
![动画](https://user-images.githubusercontent.com/117004316/210793053-253aec38-7a14-4003-ab71-45680b2b79ab.gif)

**Comment by TfTHacker** [comment]
Oh I am sorry to see this. I am working on an update that should come out in a day or two. Please give this a try with 1.2.0 when available.
