### ISSUE TITLE
[Bug]: Body of note off center from the title

### ISSUE THREAD

**Issue by mk-uc** [TfTHacker/obsidian42-strange-new-worlds#74]
With the plugin activated, the body of the note is off center from the title, as you can see from the screenshot. Disable the plugin and it goes back to normal..

![Screenshot 2023-01-06 at 10 32 25 AM](https://user-images.githubusercontent.com/7539590/211058406-35a412c1-f015-45fc-acf5-8c1322a9cc6e.png)

**Comment by TfTHacker** [comment]
SNW uses a gutter. This can be turned off in settings (See embed references in the gutter). 

Themes control gutters. If you switch to "Minimal" theme, you'll see this disappear.

Additionally, with SNW off and Line numbers enabled, which also use gutters, you'll see the same effect.

So not really a bug, but confusing for sure  😄  Hopefully, this will help.
