### ISSUE TITLE
Capitalization not recognized

### ISSUE THREAD

**Issue by Comprehensive-Jason** [TfTHacker/obsidian42-strange-new-worlds#75]
The Strange New Worlds plugin does not count capitalized backlinks in the same way that Obsidian does. 

For example, Obsidian is case insensitive and considers both [[Productivity]] and [[productivity]] to be backlinks to the same page, but Strange New Worlds counts them differently:
![image](https://user-images.githubusercontent.com/68677082/211109114-ab46085f-80b1-4608-9077-9398c573e48e.png)

Is there a good reason for this behavior? If not, could Strange New World be made case-insensitive to match Obsidian?

**Comment by TfTHacker** [comment]
Thank you for reporting this. This should be addressed with release 1.2.0 coming out here soon.
