### ISSUE TITLE
Reference shows in wrong spot in reading view

### ISSUE THREAD

**Issue by sawft99** [TfTHacker/obsidian42-strange-new-worlds#76]
I am not sure if these are all related but I noticed various issues in how the reference number was showing up in the right spot in editing view but incorrectly in the reading view.

- An extra space below a reference (Pic4)
- The reference showing in the wrong spot and with a space on many others (All other pictures). Some of the references are in completely different parts of the document as well

My files:

- https://github.com/sawft99/Obsidian-SecPlus/blob/main/Sec+/Chapter%201%20-%20Overview/SecBasics.md
- https://github.com/sawft99/Obsidian-SecPlus/blob/main/Sec+/About/Objectives.md

Edit:

It seems to matter where a reference (^######) is in a bullet point. It shows in the area above the parent one.

![1](https://user-images.githubusercontent.com/81699231/215854003-901664d7-aa21-477d-a96a-6f169b874779.png)
![2](https://user-images.githubusercontent.com/81699231/215854016-4a772deb-af5e-425a-a9ce-c8816a9aa924.png)
![3](https://user-images.githubusercontent.com/81699231/215854039-74404319-217b-4542-ad66-f5cc7f8cb903.png)
![4](https://user-images.githubusercontent.com/81699231/215854044-e0c77b1c-c760-4eb0-a923-25dd3dbd8b0c.png)
![5](https://user-images.githubusercontent.com/81699231/215854071-1ef01347-5d5c-4f25-9fbc-f963fd60d751.png)
![6](https://user-images.githubusercontent.com/81699231/215854084-fe28f048-cfd7-4c85-94ee-ae3abd6576dd.png)

**Comment by erichalldev** [comment]
I'm experiencing the same thing. It appears to work fine in editing mode, but not reading mode. It will also ignore any block with a reference except the first one in a bulleted list.

<img width="1377" alt="Screen Shot 2023-02-20 at 1 26 52 PM" src="https://user-images.githubusercontent.com/5632228/220190797-aa6aae69-da3b-4753-8b19-57ac56cd2377.png">

<img width="1381" alt="Screen Shot 2023-02-20 at 1 27 21 PM 1" src="https://user-images.githubusercontent.com/5632228/220190818-1fda8756-5680-456a-bdd4-ab395088c67f.png">
