### ISSUE TITLE
Reference counter not working for in-page references

### ISSUE THREAD

**Issue by AnweshGangula** [TfTHacker/obsidian42-strange-new-worlds#77]
In Obsidian, when you're referencing a block or heading in the same page/note - you don't need to specify the file name. For example you can use `[[#Heading2]` or `[[#^block-reference]]` to add a reference withing the same page.

but SNW doesn't recognize this, and it doesn't add the reference counter for these. Below is a screenshot of the issue in action.

![Screenshot showing the reference counter in Obsidian for SNW](https://user-images.githubusercontent.com/22996896/215989133-38c0af45-4af3-4579-892d-e9477c9aafb6.png)

**Comment by TfTHacker** [comment]
Well, this one was a pain! I think I have it fixed. It should be released soon with 1.2.0 update to SNW. Thank you for reporting the issue.
