### ISSUE TITLE
The block quote in the same file cannot be count

### ISSUE THREAD

**Issue by Yubuxin** [TfTHacker/obsidian42-strange-new-worlds#8]
I don't know if this was deliberately designed, but I think it's very important to show the quote in the same file, because the text within a single file may become very long and difficult to find the location of quotes.

And, quoting of blocks in the same file should be a common operation when use the daily note workflow.

**Comment by TfTHacker** [comment]
Thank you for your feedback. Can you find me an example do I can be sure to understand in detail. I am sure it's possible 🤠

**Comment by TfTHacker** [comment]
Do you mean like this?

![CleanShot 2022-10-01 at 19 41 21@2x](https://user-images.githubusercontent.com/69121180/193421583-a7cea9e3-15d2-467d-b6d0-45f473d85fee.png)

**Comment by Yubuxin** [comment]
Thanks for reply. It seems right, but I didn't find this feature. Is this a preview version?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: TfTHacker ***@***.***>
发送时间: Sunday, October 2, 2022 1:42:41 AM
收件人: TfTHacker/obsidian42-strange-new-worlds ***@***.***>
抄送: KE ***@***.***>; Author ***@***.***>
主题: Re: [TfTHacker/obsidian42-strange-new-worlds] The block quote in the same file cannot be count (Issue #8)


Do you mean like this?

[CleanShot 2022-10-01 at 19 41 ***@***.***<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F69121180%2F193421583-a7cea9e3-15d2-467d-b6d0-45f473d85fee.png&data=05%7C01%7C%7Cff6bc6085b484620d6de08daa3d4576d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638002429654290297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HNWJ%2F5LYh3ZZCnHsM1Cm%2FmlZsTdweglOOJcUUWxS13Q%3D&reserved=0>

―

**Comment by TfTHacker** [comment]
I have been doing lots of updates, so maybe use BRAT to do an update and then also restart Obsidian.
