### ISSUE TITLE
Issue on display on a note with the CyberGlow theme

### ISSUE THREAD

**Issue by Mr-Tomato123** [TfTHacker/obsidian42-strange-new-worlds#81]
When looking at a note using the CyberGlow theme, the link library that is added by the plugin is obscured.

Example 
![image](https://user-images.githubusercontent.com/121110164/221884320-aaa087e9-7585-40e4-8373-b39ec9666bbb.jpeg)

**Comment by TfTHacker** [comment]
Sadly some themes do conflict with the way plugins display their content. However, using CSS you could customize the position of the incoming block reference count.

Solution is in this discussion: https://github.com/TfTHacker/obsidian42-strange-new-worlds/discussions/84
