### ISSUE TITLE
UI icon conflict with Editing Toolbar plugin in document editing view

### ISSUE THREAD

**Issue by xBlady** [TfTHacker/obsidian42-strange-new-worlds#82]
Hello!

I have a problem with UI conflict when using both SNW and Editing Toolbar plugin when viewing file in edit mode. Please make it possible to change location of SNW icon in document editing view.

![Screenshot - 2023-03-01 16 51 10](https://user-images.githubusercontent.com/7155031/222192668-44be4d48-f676-4bb1-93e9-195b87bce674.png)
![Screenshot - 2023-03-01 16 51 18](https://user-images.githubusercontent.com/7155031/222192677-f692dad8-5122-4902-a4d2-e4ea366fd246.png)

**Comment by TfTHacker** [comment]
Please find a CSS solution here at discussion number  https://github.com/TfTHacker/obsidian42-strange-new-worlds/discussions/84
