### ISSUE TITLE
Feature Request: sorting references

### ISSUE THREAD

**Issue by matclab** [TfTHacker/obsidian42-strange-new-worlds#86]
SNW looks very nice. Thank you for making it.

For my use case, it would be very helpful if the extract shown are sorted by creation date, newest first. 
Would it be possible to add an option for choosing the way things are sorted ?

**Comment by piojanu** [comment]
Similar here, but I need to sort by the modification date, the newest first. Just like you can sort backlinks in Obsidian.

**Comment by TfTHacker** [comment]
Sorting references is now possible by File name asc/desc and file modification date oldest/newst.
