### ISSUE TITLE
SNW Sidepane keeps disappearing

### ISSUE THREAD

**Issue by nestor50** [TfTHacker/obsidian42-strange-new-worlds#87]
Hello, as the title says, SNW keeps disappearing in the sidepane. If I de-activate the plugin and activate it again the icon of SNW reappears in the sidepane but after a while it disappear. I haven't been able to notice WHEN it happens. In DevTools I just see that there are three messages about "Unloading Obsidian42 Strange New Worlds plugin". Does somebody is experiencing the same issue?
Thanks!

**Comment by TfTHacker** [comment]
I dont doubt this issue exists, but its hard to reproduce. I would suggest following:
+ manually close SNW side pane (right mouse click on SNW icon in sidepane and close it)
+ uninstall plugin
+ make sure there are no remainder files in the .obsidian/plugins folder for SNW 
+ Restart obsidian
+ reinstall SNW

This is just trying to make sure there isn't some odd baggage hanging around in the internals.
