### ISSUE TITLE
Stacked/Child bullet points appear on wrong lines in reading view

### ISSUE THREAD

**Issue by sawft99** [TfTHacker/obsidian42-strange-new-worlds#89]
I reference the parent in one place and the child bullet in another creating this effect in reading view.

Edit view vs Reading view

![1](https://user-images.githubusercontent.com/81699231/229226426-2864cf02-e597-422d-aaff-aa31dcd43637.png)
![2](https://user-images.githubusercontent.com/81699231/229226452-148a5cde-08ee-4cbd-8b1b-5ce9e48443c2.png)

**Comment by TfTHacker** [comment]
I think I have fixed this. It will be available in the forthcoming 1.2.0 update. Please give it a try then, and lf it isn't working, please reopen this issue.
