### ISSUE TITLE
Conflict with better-fn plugin

### ISSUE THREAD

**Issue by ChaosNino** [TfTHacker/obsidian42-strange-new-worlds#93]
https://github.com/aidenlx/better-fn

If turn on both of plugin, the border of SNW would be dark:

![image](https://user-images.githubusercontent.com/132078093/235628542-e8177d05-d950-47a9-bd31-090224c70a11.png)

**Comment by TfTHacker** [comment]
This will be fixed with SNW 1.2.0, due to be released here shortly.

**Comment by ChaosNino** [comment]
Thank you! The problem is fixed mostly, but there are a little bugs remained:
<img width="285" alt="3028d695223b4a9c34416fa86ce8510" src="https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/132078093/b5b02263-766e-4dff-bacf-f82a0a8eb254">

**Comment by TfTHacker** [comment]
Thank you for reporting. I think I have fixed this with 1.2.1 rolling out today.
