### ISSUE TITLE
Header reference does not render when header includes a colon

### ISSUE THREAD

**Issue by rodneychu** [TfTHacker/obsidian42-strange-new-worlds#94]
In my daily notes I use a timestamp (which includes a colon separating HH:MM) as a prefix in each log entry heading.  Later on, I transclude the log entry in the relevant topic note.  I used to be able to use the reference count next to the header in the daily note to know that I've cross-referenced it but this appears to have broken.

I have confirmed that replacing the colon with an underscore makes it work again but I'd prefer to continue using colons.  I also tested with dot (being another commonly accepted time separator) but that doesn't work either.

**Comment by TfTHacker** [comment]
Thank you for reporting this issue. It'll be fixed in a release in the next day or two. I have it working and testing.
