### ISSUE TITLE
[bug] = When I input Chinese, the small digits on the link disappear

### ISSUE THREAD

**Issue by doit132** [TfTHacker/obsidian42-strange-new-worlds#96]
# Question

When I input Chinese, the small digits on the link disappear. When I input English, the small digits don't disappear. 

# Animation demonstration

![动画](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/117004316/0b515889-62f7-41d6-8b22-bf285916dc26)

# Testing environment

Obsidian Sandbox and close all plugins.

# Obsidian version

v1.3.4

**Comment by TfTHacker** [comment]
I think this might be addressed with the update in the recent beta. Please install the current beta with BRAT. If you still have an issue, please let me know by reopening this issue.
