### ISSUE TITLE
[Bug] Connections for wrong file displayed in Reading mode for non-existing note with path in link

### ISSUE THREAD

**Issue by FeralFlora** [TfTHacker/obsidian42-strange-new-worlds#97]
See this demo:

![Obsidian_daG8eulA9M](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/33608083/300bfd19-4c48-4528-a2b8-f59b3a55d191)

Three links in this one note all show "strange new worlds" connections for the same file, which is also linked in this note.

The structure of the links in question is as follows: `[[03 - Source notes/People/Anthony Leiserowitz|Anthony Leiserowitz]]`

There is a path and an alias, but the alias doesn't seem to make a difference.

I could reproduce the issue in Live-Preview, but it was inconsistent.

Also, If I copy this link into another note, the bug goes away. However, it gets even more bizarre if I insert the link that the three were pointing to into the new note.

![Obsidian_kH0uOf939b](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/33608083/d5530cdc-88b1-4b6e-ad72-250eebda917a)

Also, the [[Climate change perceptions scale]] is missing connections in this latter case.

**Comment by FeralFlora** [comment]
@TfTHacker did you see this?

**Comment by TfTHacker** [comment]
Please test and see if this issue persists with the latest beta available via BRAt. I believe this kind of issue is resolved.
