### ISSUE TITLE
[Bug] Canvas cards with headers create console error when clicking into them

### ISSUE THREAD

**Issue by xDovos** [TfTHacker/obsidian42-strange-new-worlds#98]
hey,
i found a bug where the console get's an error from this plugin when i enter a canvas card that has a header in it. the video shows how to replicate it.

https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/116905219/12410b34-d11e-42dc-b33c-e251c2dd338f

**Comment by TfTHacker** [comment]
Thank you for reporting this issue. It has been addressed.
